app_id: 2072d33d-ad75-4d38-a3eb-b22d62b3686b
app_secret: fRJZp/q[04fv]Zl5HPOF7UXcCaKulwB.
redirect: http://localhost:8000/tutorial/callback
scopes: openid profile offline_access user.read calendars.read
authority: https://login.microsoftonline.com/common
authorize_endpoint: /oauth2/v2.0/authorize
token_endpoint: /oauth2/v2.0/token